import os
import pandas as pd

class TXT2VCF:
    '''
    Transfer four-caller txt to standard VCFv4.2
    '''
    def __init__(self, input_file, output_file):
        self.input_file = input_file
        self.output_file = output_file
        print(f'Convert four-caller text file {input_file} to standard VCF file.')
    
    def read_input(self):
        """
        read input file
        """
        self.df = pd.read_csv(
            self.input_file,
            sep=r"\s+",
            dtype=str,
            header=None,
            skiprows=93
        )
        self.df.columns = ['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'AD', 'DP', 'AF']
        
    def write_header(self, vcf):
        """
        write VCF header
        """
        vcf.write("##fileformat=VCFv4.2\n")
        
        vcf.write("##source=MutKitv1.0\n")
        
        vcf.write('##website=https://github.com/yufanzhouonline/MutKit\n')
        
        vcf.write('##generation_note="This VCF file was generated by MutKit, a versatile Python package for four-caller integration of mutation calling. Author: Yufan (Harry) Zhou"\n')
        
        vcf.write('##INFO=<ID=TYPE,Number=1,Type=String,Description="Mutation type (SBS or INDEL)">\n')
        
        vcf.write(
            '##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">\n'
        )
        
        vcf.write(
            '##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">\n'
        )
        
        vcf.write(
            '##FORMAT=<ID=AF,Number=A,Type=Float,Description="Allele fractions of alternate alleles in the tumor">\n'
        )
        
        vcf.write(
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
        )
    
    def write_variants(self, vcf):
        """
        write variant records
        """
        
        for _, row in self.df.iterrows():
            
            info = 'INFO=TYPE=SBS' if len(row['REF']) == 1 and len(row['ALT']) == 1 else 'INFO=TYPE=INDEL'
            fmt = "AD:DP:AF"
            
            sample = (
                f"{row['AD']}:"
                f"{row['DP']}:"
                f"{row['AF']}"
            )
            
            line = (
                f"{row['CHROM']}\t"
                f"{row['POS']}\t"
                f"{row['ID']}\t"
                f"{row['REF']}\t"
                f"{row['ALT']}\t"
                f"{row['QUAL']}\t"
                f"{row['FILTER']}\t"
                f"{info}\t"
                f"{fmt}\t"
                f"{sample}\n"
            )
            
            vcf.write(line)
    
    def convert(self):
        """
        main function
        """
        self.read_input()
        
        with open(self.output_file, "w") as vcf:
            
            self.write_header(vcf)
            
            self.write_variants(vcf)
            
        print(f"VCF written to: {self.output_file}")

if __name__ == "__main__":
    input_path = '/path/of/four-caller/vcfs/'
    output_path = '/path/of/revised/vcfs/'
    file_list = os.listdir(input_path)
    for filename in file_list:
        outputname = filename[:-4] + '.revised.vcf'
        converter = TXT2VCF(input_file=input_path+filename, output_file=output_path+filename)
        converter.convert()
